coba

diff --git a/.github/workflows/internship.yml b/.github/workflows/internship.yml
--- a/.github/workflows/internship.yml
+++ b/.github/workflows/internship.yml
@@ -1,10 +1,10 @@
-name: CI/CD
+name: CI/CD Laravel Deployment
 
 on:
   push:
     branches:
       - master
-  
+
 jobs:
   deploy-laravel-vps:
     runs-on: ubuntu-latest
@@ -28,7 +28,7 @@ jobs:
       uses: actions/checkout@v4
 
     - name: Setup PHP
-      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
+      uses: shivammathur/setup-php@2.27.0
       with:
         php-version: '8.3'
         extensions: mbstring, pdo, pdo_mysql, zip, bcmath
@@ -38,13 +38,16 @@ jobs:
       run: cp .env.example .env
 
     - name: Set Directory Permissions (Pre-Key Generate)
-      run: chmod -R 775 storage bootstrap/cache
-
-    - name: Install Dependencies
-      run: composer install --no-interaction --prefer-dist --optimize-autoloader
+      run: |
+        sudo chmod 777 .env
+        sudo chmod -R 775 storage bootstrap/cache
+        sudo chown -R www-data:www-data storage bootstrap/cache
 
     - name: Generate Application Key
-      run: php artisan key:generate
+      run: sudo php artisan key:generate
+
+    - name: Debug: Check .env Existence
+      run: ls -lah .env && cat .env | grep APP_KEY || echo ".env is missing!"
 
     - name: Wait for MySQL to be Ready
       run: |
@@ -66,7 +69,7 @@ jobs:
         DB_DATABASE: ratu_report
         DB_USERNAME: root
         DB_PASSWORD: root
-      run: php artisan migrate
+      run: php artisan migrate --force
 
     - name: Setup SSH Connection
       run: |
@@ -78,7 +81,7 @@ jobs:
     - name: Test SSH Connection
       run: ssh -i ~/.ssh/ratu_key -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.IP }} "echo SSH sukses!"
 
-    - name: SSH and Deploy to VPS
+    - name: SSH and Deploy App
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.IP }}
@@ -86,6 +89,12 @@ jobs:
         key: ${{ secrets.SSH_KEY }}
         script: |
           cd /var/www/html/InternshipLogistik
+          
+          if [ ! -f .env ]; then
+            cp .env.example .env
+            php artisan key:generate
+          fi
+
           sudo git pull origin master
 
           sudo chown -R www-data:www-data storage bootstrap/cache
@@ -93,8 +102,8 @@ jobs:
           sudo chmod 777 .env
 
           composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
-          php artisan migrate
-
+    
+          php artisan migrate --force
           php artisan config:clear
           php artisan cache:clear
           php artisan route:clear
